Updated changes for Ubuntu 18.04 LTS
connorkuehl/connorkuehl.github.io pull request #5
Opened 2018-07-10 23:17 UTC by rambabugovind

Hey Connor,
I still have the Dell Inspiron 7559 laptop and installed Ubuntu 18.04 LTS on it. Your doc was really helpful and I thought I could update my experience with installing 18.04 LTS in the laptop. Thanks much.

2018-07-11 02:47 UTC, connorkuehl requested changes
Thank you for taking the time to contribute to this!

I like the changes you made, but there are just a couple of typos I'd like fixed before I merge this.

Also, the blue boxes that say "Follow the below steps for 18.04 LTS installation as well." seem redundant due to your disclaimer at the beginning that says "Text within blue boxes indicates instructions intended only for Ubuntu Linux 18.04 LTS. The sections that were tested with Ubuntu Linux 18.04 LTS will be explicitly stated. "

2018-07-11 02:47 UTC, connorkuehl commented on dell-inspiron-7559-linux-guide/index.html
> +                <p class="note note-warn">Donot try to upgrade from
"Donot" -> "Do not"

2018-07-11 02:47 UTC, connorkuehl commented on dell-inspiron-7559-linux-guide/index.html
> +                <a href="https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes">late july</a>.
I'd suggest linking directly to the relevant section: [https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes#Upgrading_from_Ubuntu_16.04_LTS](https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes#Upgrading_from_Ubuntu_16.04_LTS)

2018-07-11 02:47 UTC, connorkuehl commented on dell-inspiron-7559-linux-guide/index.html
> +                <p class="note note-18"><b>Didnot</b> test this section with <b>18.04 LTS</b> installation.</p>
"Didnot" -> "Did not"

2018-07-11 02:47 UTC, connorkuehl commented on dell-inspiron-7559-linux-guide/index.html
> +                <p class="note note-18"><b>Didnot</b> test this section with <b>18.04 LTS</b> installation.</p>
"Didnot" -> "Did not"

2018-07-11 02:47 UTC, connorkuehl commented on dell-inspiron-7559-linux-guide/index.html
> +                <p class="note note-18"><b>Didnot</b> test this section with <b>18.04 LTS</b> installation.</p>
"Didnot" -> "Did not"

2018-07-11 02:47 UTC, connorkuehl commented on dell-inspiron-7559-linux-guide/index.html
> +                <p class="note note-18"><b>Didnot</b> test this section with <b>18.04 LTS</b> installation.</p>
"Didnot" -> "Did not"

2018-07-11 04:18 UTC, rambabugovind commented
Thanks a lot for getting back and thanks for letting me know of the changes. I’ll make the relevant changes and open a new PR.

2018-07-11 04:20 UTC, connorkuehl commented
You can just push to your branch and this PR will be updated automatically.

On Tue, Jul 10, 2018 at 9:18 PM rambabugovind <notifications@github.com>
wrote:

> Thanks a lot for getting back and thanks for letting me know of the
> changes. I’ll make the relevant changes and open a new PR.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/connorkuehl/connorkuehl.github.io/pull/5#issuecomment-404040050>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AE_DSqJvzhDJcJdqfyY3Gg9w-IJlX_n3ks5uFXx6gaJpZM4VKQnO>
> .
>

2018-07-11 15:31 UTC, rambabugovind commented
Hey Connor, I have fixed the mentioned typos and the link. Let me know if there are any other changes.

2018-07-12 01:48 UTC, connorkuehl approved these changes

2018-07-12 01:49 UTC, merged

2018-07-12 01:49 UTC, connorkuehl commented
Thank you!